/*
let nome = "Isabella"
const idade = "25"
console.log ("Olá me chamo",nome, "e tenho", idade)

let preco = 50;
let desconto = 20;
let precofinal = preco - desconto
console.log (precofinal); // saída 30

const fruta = ["Morango", "pitaya", "uva"]
console.log (fruta[1])


let livro = {
  Nome: 'O Menino do Pijama Listrado',
  Autor: 'John Boyn',
  Ano: '2007'
};

console.log ('Estou lendo um livro chamado',livro.Nome, 'e o autor se chama',livro.Autor)


let estaLogado = false; 
estaLogado = true; 

console.log(estaLogado)

*/
const PI = 3.14;
let Raio = 5
console.log((2*PI)*Raio)